#? Config file for btop v. 1.4.7

# Color theme (looks in ~/.config/btop/themes and /usr/share/btop/themes)
color_theme = "tokyo-night"

# If empty, the theme's background color is used
theme_background = True

# Use 24-bit truecolor
truecolor = True

# Enable vim keys (h,j,k,l) for navigation
vim_keys = True

# Rounded corners on boxes
rounded_corners = True

# Graph symbol: default, braille, block or tty
graph_symbol = "braille"

# Update time in milliseconds
update_ms = 1000

# Show a clock at the top of the CPU box
clock_format = "%X"

# Temperature scale
temp_scale = "celsius"

# Base 2 (1024) memory units
base_10_sizes = False
